---
title: "Communication"
output:
  html_document: 
    toc: true
    toc_float: true
---

<br>

### *Email*

They are here to address any questions or clarifications you may have. If you would like to communicate with the Biostatistics Core, please feel free to reach out to Justin Kinney or Taehoon Ha via email.

+ Justin Kinney (Faculty Head): [jkinney@cshl.edu](mailto:jkinney@cshl.edu)
+ Taehoon Ha (Core Director): [ha@cshl.edu](mailto:ha@cshl.edu)

They will be happy to assist with any course-related inquiries or provide further guidance. Please include a clear subject line and a detailed message to ensure a prompt and efficient response. Take advantage of this opportunity to reach out with your questions or concerns. They are dedicated to supporting your learning experience throughout the course.

<br>

### *Biostatistics Office Hour*

🕑 **When: Thursdays, 2-4 pm**

Welcome to our Cancer-Center-sponsored core resource! Our aim is to support and enhance statistical collaboration in biomedical research at Cold Spring Harbor Laboratory.

👉 **What to expect:**
Get one-hour of complimentary statistical advice tailored to your research needs. Exclusively available for CSHL Cancer Center faculty, staff, and students.

📧 **How to schedule an appointment:**

<!-- Calendly link widget begin -->
<link href="https://assets.calendly.com/assets/external/widget.css" rel="stylesheet">
<script src="https://assets.calendly.com/assets/external/widget.js" type="text/javascript"></script>
<a href="" onclick="Calendly.initPopupWidget({url: 'https://calendly.com/cshlbiostat'});return false;">Schedule time with Taehoon</a>
<!-- Calendly link widget end -->