<!DOCTYPE html>

<html>

<head>

<meta charset="utf-8" />
<meta name="generator" content="pandoc" />
<meta http-equiv="X-UA-Compatible" content="IE=EDGE" />




<title>Week 5-1. Bootstrap hypothesis testing &amp; normal
approximation</title>

<script src="site_libs/header-attrs-2.16/header-attrs.js"></script>
<script src="site_libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<meta name="viewport" content="width=device-width, initial-scale=1" />
<link href="site_libs/bootstrap-3.3.5/css/cosmo.min.css" rel="stylesheet" />
<script src="site_libs/bootstrap-3.3.5/js/bootstrap.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/html5shiv.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/respond.min.js"></script>
<style>h1 {font-size: 34px;}
       h1.title {font-size: 38px;}
       h2 {font-size: 30px;}
       h3 {font-size: 24px;}
       h4 {font-size: 18px;}
       h5 {font-size: 16px;}
       h6 {font-size: 12px;}
       code {color: inherit; background-color: rgba(0, 0, 0, 0.04);}
       pre:not([class]) { background-color: white }</style>
<script src="site_libs/jqueryui-1.11.4/jquery-ui.min.js"></script>
<link href="site_libs/tocify-1.9.1/jquery.tocify.css" rel="stylesheet" />
<script src="site_libs/tocify-1.9.1/jquery.tocify.js"></script>
<script src="site_libs/navigation-1.1/tabsets.js"></script>
<link href="site_libs/highlightjs-9.12.0/default.css" rel="stylesheet" />
<script src="site_libs/highlightjs-9.12.0/highlight.js"></script>
<link href="site_libs/font-awesome-5.1.0/css/all.css" rel="stylesheet" />
<link href="site_libs/font-awesome-5.1.0/css/v4-shims.css" rel="stylesheet" />

<style type="text/css">
  code{white-space: pre-wrap;}
  span.smallcaps{font-variant: small-caps;}
  span.underline{text-decoration: underline;}
  div.column{display: inline-block; vertical-align: top; width: 50%;}
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
  ul.task-list{list-style: none;}
    </style>

<style type="text/css">code{white-space: pre;}</style>
<script type="text/javascript">
if (window.hljs) {
  hljs.configure({languages: []});
  hljs.initHighlightingOnLoad();
  if (document.readyState && document.readyState === "complete") {
    window.setTimeout(function() { hljs.initHighlighting(); }, 0);
  }
}
</script>






<link rel="stylesheet" href="styles.css" type="text/css" />



<style type = "text/css">
.main-container {
  max-width: 940px;
  margin-left: auto;
  margin-right: auto;
}
img {
  max-width:100%;
}
.tabbed-pane {
  padding-top: 12px;
}
.html-widget {
  margin-bottom: 20px;
}
button.code-folding-btn:focus {
  outline: none;
}
summary {
  display: list-item;
}
details > summary > p:only-child {
  display: inline;
}
pre code {
  padding: 0;
}
</style>


<style type="text/css">
.dropdown-submenu {
  position: relative;
}
.dropdown-submenu>.dropdown-menu {
  top: 0;
  left: 100%;
  margin-top: -6px;
  margin-left: -1px;
  border-radius: 0 6px 6px 6px;
}
.dropdown-submenu:hover>.dropdown-menu {
  display: block;
}
.dropdown-submenu>a:after {
  display: block;
  content: " ";
  float: right;
  width: 0;
  height: 0;
  border-color: transparent;
  border-style: solid;
  border-width: 5px 0 5px 5px;
  border-left-color: #cccccc;
  margin-top: 5px;
  margin-right: -10px;
}
.dropdown-submenu:hover>a:after {
  border-left-color: #adb5bd;
}
.dropdown-submenu.pull-left {
  float: none;
}
.dropdown-submenu.pull-left>.dropdown-menu {
  left: -100%;
  margin-left: 10px;
  border-radius: 6px 0 6px 6px;
}
</style>

<script type="text/javascript">
// manage active state of menu based on current page
$(document).ready(function () {
  // active menu anchor
  href = window.location.pathname
  href = href.substr(href.lastIndexOf('/') + 1)
  if (href === "")
    href = "index.html";
  var menuAnchor = $('a[href="' + href + '"]');

  // mark the anchor link active (and if it's in a dropdown, also mark that active)
  var dropdown = menuAnchor.closest('li.dropdown');
  if (window.bootstrap) { // Bootstrap 4+
    menuAnchor.addClass('active');
    dropdown.find('> .dropdown-toggle').addClass('active');
  } else { // Bootstrap 3
    menuAnchor.parent().addClass('active');
    dropdown.addClass('active');
  }

  // Navbar adjustments
  var navHeight = $(".navbar").first().height() + 15;
  var style = document.createElement('style');
  var pt = "padding-top: " + navHeight + "px; ";
  var mt = "margin-top: -" + navHeight + "px; ";
  var css = "";
  // offset scroll position for anchor links (for fixed navbar)
  for (var i = 1; i <= 6; i++) {
    css += ".section h" + i + "{ " + pt + mt + "}\n";
  }
  style.innerHTML = "body {" + pt + "padding-bottom: 40px; }\n" + css;
  document.head.appendChild(style);
});
</script>

<!-- tabsets -->

<style type="text/css">
.tabset-dropdown > .nav-tabs {
  display: inline-table;
  max-height: 500px;
  min-height: 44px;
  overflow-y: auto;
  border: 1px solid #ddd;
  border-radius: 4px;
}

.tabset-dropdown > .nav-tabs > li.active:before {
  content: "";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li.active:before {
  content: "&#xe258;";
  border: none;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open:before {
  content: "";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs > li.active {
  display: block;
}

.tabset-dropdown > .nav-tabs > li > a,
.tabset-dropdown > .nav-tabs > li > a:focus,
.tabset-dropdown > .nav-tabs > li > a:hover {
  border: none;
  display: inline-block;
  border-radius: 4px;
  background-color: transparent;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li {
  display: block;
  float: none;
}

.tabset-dropdown > .nav-tabs > li {
  display: none;
}
</style>

<!-- code folding -->



<style type="text/css">

#TOC {
  margin: 25px 0px 20px 0px;
}
@media (max-width: 768px) {
#TOC {
  position: relative;
  width: 100%;
}
}

@media print {
.toc-content {
  /* see https://github.com/w3c/csswg-drafts/issues/4434 */
  float: right;
}
}

.toc-content {
  padding-left: 30px;
  padding-right: 40px;
}

div.main-container {
  max-width: 1200px;
}

div.tocify {
  width: 20%;
  max-width: 260px;
  max-height: 85%;
}

@media (min-width: 768px) and (max-width: 991px) {
  div.tocify {
    width: 25%;
  }
}

@media (max-width: 767px) {
  div.tocify {
    width: 100%;
    max-width: none;
  }
}

.tocify ul, .tocify li {
  line-height: 20px;
}

.tocify-subheader .tocify-item {
  font-size: 0.90em;
}

.tocify .list-group-item {
  border-radius: 0px;
}

.tocify-subheader {
  display: inline;
}
.tocify-subheader .tocify-item {
  font-size: 0.95em;
}

</style>



</head>

<body>


<div class="container-fluid main-container">


<!-- setup 3col/9col grid for toc_float and main content  -->
<div class="row">
<div class="col-xs-12 col-sm-4 col-md-3">
<div id="TOC" class="tocify">
</div>
</div>

<div class="toc-content col-xs-12 col-sm-8 col-md-9">




<div class="navbar navbar-default  navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-bs-toggle="collapse" data-target="#navbar" data-bs-target="#navbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="index.html">Cold Spring Harbor Laboratory Biostatistics</a>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
    Services
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
    <li>
      <a href="services.html">Basic Services</a>
    </li>
    <li>
      <a href="grant_application.html">Grant Application Help</a>
    </li>
    <li class="dropdown-header">Research Collaboration</li>
  </ul>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
    Training
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
    <li>
      <a href="biostatistics_course.html">Biostatistics Course (Summer)</a>
    </li>
    <li>
      <a href="toc.html">Intro to Biostatistics with R</a>
    </li>
  </ul>
</li>
<li>
  <a href="https://github.com/taehoonh/CSHLbiostat">
    <span class="fa fa-github"></span>
     
  </a>
</li>
      </ul>
    </div><!--/.nav-collapse -->
  </div><!--/.container -->
</div><!--/.navbar -->

<div id="header">




</div>


<!-- <link rel="stylesheet" href="styles.css" type="text/css"> -->
<p><br><br><br></p>
<p><a href="toc.html">&lt; Back to Syllabus</a></p>
<p><br><br><br></p>
<div id="pharmacology-example" class="section level3">
<h3>1. Pharmacology example</h3>
<p>One method for assessing the bio availability of a drug is to note
its concentration in blood and/or urine samples at certain period of
time after the drug is given. Suppose we want to compare the
concentrations of two types of aspirin (Types A and B) in urine
specimens taken from the the same person 1 hour after she or he has
taken the drug. Hence, a specific dosage of either Type A or Type B
aspirin is given at one time and the 1-hour urine concentration is
measured. One week later, after the aspirin has presumably been cleared
from the system, the same dosage of the other aspirin is given to the
same person and the 1-hour urine concentration is noted. Because the
order of giving the drugs may affect the result, patients were
randomized to either take A first (then one week later B) or to take B
first (and then one week later A). This experiment was performed on 25
people. The data are found in a file called <a
href="./data/aspirin.csv"><code>aspirin.csv</code></a>.</p>
<p>Read the data into R and save in an object called
<code>aspirinPharm</code>.</p>
<pre class="r"><code>aspirinPharm &lt;- read.csv(&quot;./data/aspirin.csv&quot;)
head(aspirinPharm)</code></pre>
<pre><code>##   subjID Avals Bvals
## 1   s372  22.0  20.0
## 2   s268  24.9  16.1
## 3   s281  23.1  29.1
## 4   s328  10.0  12.8
## 5   s314  18.8  16.9
## 6   s384  36.1  18.0</code></pre>
<p>The column <code>Avals</code> contains the aspirin A 1-hour
concentration (mg%) and the column <code>Bvals</code> contains the
aspirin B 1-hour concentration (mg%). The column <code>subjID</code> is
the id number of the subject.</p>
<p><br><br></p>
</div>
<div id="approximate-sampling-distribution" class="section level3">
<h3>2. Approximate sampling distribution</h3>
<ul>
<li>We are interested in the mean concentration levels of each of the
different aspirins.</li>
<li>Our focus will first be on Aspirin A. We are interested in <span
class="math inline">\(\mu\)</span>, the true mean concentration level
for aspirin A.</li>
<li>Intuitively, we would use the sample mean to estimate <span
class="math inline">\(\mu\)</span>.</li>
<li>Specifically the sample mean would be obtained with the
<code>R</code> function <code>mean()</code>.</li>
<li>In this case, the sample mean is 20.9.</li>
<li>However, we know that the sample mean likely will not equal the
population mean, <span class="math inline">\(\mu\)</span>.</li>
<li>Specifically, different samples of the same sample sizes will yield
different sample means.</li>
<li>The question is **how can we gauge the accuracy of 20.9 as an
estimate of <span class="math inline">\(\mu\)</span>?</li>
</ul>
<p><br></p>
<div id="sampling-distribution" class="section level4">
<h4>2.0 Sampling distribution</h4>
<ul>
<li>If we had the sampling distribution for the sample means for samples
of size 25 from the population, then this would give us an idea of how
the sample means vary from sample to sample.</li>
<li>Looking at the spread of the sampling distribution of the sample
means, measured by the standard deviation, we can get a sense of how far
sample means can deviate from the population mean, <span
class="math inline">\(\mu\)</span>.</li>
<li>However, since we cannot afford to give aspirin A to the entire
population and measure the concentrations, <strong>we cannot generate
the sampling distribution</strong>.</li>
</ul>
<p><br></p>
<blockquote>
<p>Note if we did give aspirin A to the entire population and measured
the concentrations in the urine, we would know the population mean
value!</p>
</blockquote>
<p><br></p>
</div>
<div id="review-bootstrap-distribution" class="section level4">
<h4>2.1 Review bootstrap distribution</h4>
<ul>
<li><strong>Bootstrap</strong> is a procedure that uses the given sample
to create a bootstrap distribution, that approximates the sampling
distribution for the sample statistic, which in this case would be the
sample mean.</li>
<li>We’ll use a small subset of the urine concentrations levels: 22,
24.9, 23.1.</li>
<li><strong>To find the bootstrap distribution of the mean</strong>,
<ul>
<li>draw samples (bootstrap sample) of size <span
class="math inline">\(n\)</span>, with replacement, from the original
sample and then</li>
<li>compute the mean of each resample.</li>
</ul></li>
<li>The original sample of size 3 is the <strong>population</strong>.
<ul>
<li>There are <span class="math inline">\(3^3=27\)</span> samples of
size 3, taking order in which they are drawn into account.</li>
<li>From this, we can compute the <strong>sample mean</strong> for each
of the 27 samples.</li>
</ul></li>
</ul>
<p><br></p>
<ul>
<li>All 27 samples of size 3
<ul>
<li><span class="math inline">\(x_1^*\)</span>: resampled
observation</li>
<li><span class="math inline">\(x_2^*\)</span>: resampled
observation</li>
<li><span class="math inline">\(x_3^*\)</span>: resampled
observation</li>
<li><span class="math inline">\(\bar{x^*}\)</span>: statistic of
interest (sample mean in this case)</li>
</ul></li>
</ul>
<p><span class="math display">\[
\begin{array}{llll}\hline x_{1}^{*} &amp; x_{2}^{*} &amp; x_{3}^{*}
&amp; \bar{x}^{*} \\ \hline 22.0 &amp; 22.0 &amp; 22.0 &amp; 22.0 \\
22.0 &amp; 22.0 &amp; 24.9 &amp; 23.0 \\ 22.0 &amp; 22.0 &amp; 23.1
&amp; 22.4 \\ 22.0 &amp; 24.9 &amp; 22.0 &amp; 23.0 \\ 22.0 &amp; 24.9
&amp; 24.9 &amp; 23.9 \\ 22.0 &amp; 24.9 &amp; 23.1 &amp; 23.3 \\ 22.0
&amp; 23.1 &amp; 22.0 &amp; 22.4 \\ 22.0 &amp; 23.1 &amp; 24.9 &amp;
23.3 \\ 22.0 &amp; 23.1 &amp; 23.1 &amp; 22.7 \\ 24.9 &amp; 22.0 &amp;
22.0 &amp; 23.0 \\ 24.9 &amp; 22.0 &amp; 24.9 &amp; 23.9 \\ 24.9 &amp;
22.0 &amp; 23.1 &amp; 23.3 \\ 24.9 &amp; 24.9 &amp; 22.0 &amp; 23.9 \\
24.9 &amp; 24.9 &amp; 24.9 &amp; 24.9 \\ 24.9 &amp; 24.9 &amp; 23.1
&amp; 24.3 \\ 24.9 &amp; 23.1 &amp; 22.0 &amp; 23.3 \\ 24.9 &amp; 23.1
&amp; 23.1 &amp; 23.7 \\ 24.9 &amp; 23.1 &amp; 24.9 &amp; 24.3 \\ 23.1
&amp; 22.0 &amp; 22.0 &amp; 22.4 \\ 23.1 &amp; 22.0 &amp; 24.9 &amp;
23.3 \\ 23.1 &amp; 22.0 &amp; 23.1 &amp; 22.7 \\ 23.1 &amp; 24.9 &amp;
22.0 &amp; 23.3 \\ 23.1 &amp; 24.9 &amp; 24.9 &amp; 24.3 \\ 23.1 &amp;
24.9 &amp; 23.1 &amp; 23.7 \\ 23.1 &amp; 23.1 &amp; 22.0 &amp; 22.7 \\
23.1 &amp; 23.1 &amp; 24.9 &amp; 23.7 \\ 23.1 &amp; 23.1 &amp; 23.1
&amp; 23.1 \\ \hline\end{array}
\]</span></p>
<ul>
<li><code>R</code>: the sampling distribution is based on a sample of
size 3.</li>
</ul>
<pre class="r"><code>sample &lt;- aspirinPharm$Avals[1:3] # c(22, 24.9, 23.1)

hist(xbarDist, freq=F, xlab=&quot;sample mean&quot;, ylab=&quot;proportion&quot;, main=&quot;Sample Distribution for Sample Mean (n = 3)&quot;, col=&quot;lavender&quot;, breaks = 6)</code></pre>
<p><img src="stat_seminar_wk05-1_files/figure-html/unnamed-chunk-4-1.png" width="672" /></p>
<ul>
<li>The idea behind the bootstrap is that
<ul>
<li>if the original sample is representative of the population, then the
bootstrap distribution of the mean will look approximately like the
sampling distribution of the mean;</li>
<li>that is, have roughly the same spread and shape.</li>
</ul></li>
<li>However, the mean of the bootstrap distribution will be the same as
the mean of the original sample, but not necessarily that of the
original population.
<ul>
<li>Thus, in the lecture 7, we already said that the bootstrap
distribution is not a good estimate of population mean.</li>
</ul></li>
<li><strong>Summary</strong>:
<ul>
<li>can use the bootstrap sample to approximate the spread of the real
sampling distribution and to approximate the shape of the real sampling
distribution.</li>
<li>cannot use it to approximate the population mean, <span
class="math inline">\(\mu\)</span>.
<ul>
<li>To estimate the population mean, <span
class="math inline">\(\mu\)</span>, we will use the sample mean of the
original sample. (<strong>point estimate</strong>)</li>
</ul></li>
</ul></li>
</ul>
<p><br></p>
<blockquote>
<p><strong>Bootstrap Idea</strong></p>
<ul>
<li>The original sample approximates the population from which it is
drawn.</li>
<li>Resamples from this sample approximate what we would get if we took
many samples from the population.</li>
<li>The bootstrap distribution of a statistic, based on many resamples,
approximates the sampling distribution of the statistic, based on many
samples.</li>
</ul>
</blockquote>
<p><br></p>
<ul>
<li>Now let’s work with the full data set.
<ul>
<li>Draw resamples of size <span class="math inline">\(n=25\)</span>
from the 25 concentration levels for aspirin A and calculate the mean
for each.</li>
<li>There are now <span class="math inline">\(25^25\)</span> samples.
(too many)</li>
<li>Instead we draw samples randomly, of size 25, with replacement, from
the data, and calculate the mean for each.</li>
<li>We repeat this process many times, say <span
class="math inline">\(B=7500\)</span>, to create the <strong>bootstrap
distribution</strong>.</li>
</ul></li>
<li>Imagine that there is a table similar to the one above but with
<span class="math inline">\(25^25\)</span> rows (as a sample
space).</li>
<li>We will randomly pick 7500 rows out of <span
class="math inline">\(25^25\)</span> rows.</li>
</ul>
<blockquote>
<p><strong>Bootstrap for a Single Population</strong></p>
<ul>
<li>Given a sample of size <span class="math inline">\(n\)</span> from a
population.
<ul>
<li>&lt;1&gt; Draw a resample of size <span
class="math inline">\(n\)</span> with replacement from the sample.
Compute a statistic that describes the sample such as the sample
mean.</li>
<li>&lt;2&gt; Repeat the resampling process many times, say between 5000
and 10000.</li>
<li>&lt;3&gt; Construct the bootstrap distribution of the statistic.
Inspect its spread, bias, and shape.</li>
</ul></li>
</ul>
</blockquote>
<p><br></p>
</div>
<div id="example" class="section level4">
<h4>2.2 Example</h4>
<p>For our example, we would estimate the mean urine concentration
1-hour after ingesting aspirin A using the <strong>sample mean,
20.9</strong>. In addition to the point estimate, we would like a
<strong>90% confidence interval</strong>. Since we do not know the
sample distribution for the sample mean, we will do a bootstrap.
Specifically, we will estimate the sampling distribution for the sample
mean based on <strong><span
class="math inline">\(B=7500\)</span></strong> bootstrapped samples.</p>
<ul>
<li>‘manual’ bootstrapped sample and its distribution</li>
</ul>
<pre class="r"><code>B &lt;- 7500
n &lt;- length(aspirinPharm$Avals) 
xbar &lt;- replicate(B,
                  { 
                    x &lt;- sample(aspirinPharm$Avals, size = n, replace = T) 
                    mean(x)
                    }
                  )</code></pre>
<pre class="r"><code>hist(xbar, probability = T, breaks=20,
     col=&quot;lemonchiffon&quot;,
     xlab=&quot;sample mean&quot;,
     ylab = &quot;probability&quot;,
     main = &quot;Estimate of the sampling distribution of sample mean&quot;)
lines(density(xbar), col=2, lwd=3) 
legend(&quot;topright&quot;, &quot;density&quot;, col=2, lwd=3)</code></pre>
<p><img src="stat_seminar_wk05-1_files/figure-html/unnamed-chunk-6-1.png" width="672" /></p>
<ul>
<li>the sample mean of the approximate sampling distribution of the
sample mean and the standard deviation of the sampling distribution of
the sample mean (i.e. standard error)</li>
</ul>
<pre class="r"><code># mean
mean(xbar) %&gt;% round(1)</code></pre>
<pre><code>## [1] 21</code></pre>
<pre class="r"><code># standard deviation
sd(xbar) %&gt;% round(2)</code></pre>
<pre><code>## [1] 1.31</code></pre>
<ul>
<li>compare the <strong>distribution of the original sample</strong> to
that of the <strong>approximation of the sample distribution for the
sample mean</strong>.</li>
</ul>
<pre class="r"><code>par(mfrow = c(1,2))
hist(aspirinPharm$Avals, freq = F, breaks = 10, 
     xlim=c(min(aspirinPharm$Avals),
            max(aspirinPharm$Avals)),
     col=&quot;lemonchiffon&quot;,
     xlab=&quot;concentration&quot;,
     ylab = &quot;probability&quot;,
     main = &quot;Concentrations Disribution&quot;)
lines(density(aspirinPharm$Avals), col=6, lwd=3) 
hist(xbar, probability = T, breaks=20, 
     xlim=c(min(aspirinPharm$Avals),
            max(aspirinPharm$Avals)), 
     col=&quot;lemonchiffon&quot;, 
     xlab=&quot;sample mean&quot;,
     ylab = &quot;probability&quot;,
     main = &quot;Sample Dist of Sample Mean&quot;)
lines(density(xbar), col=6, lwd=3)</code></pre>
<p><img src="stat_seminar_wk05-1_files/figure-html/unnamed-chunk-8-1.png" width="672" /></p>
<ul>
<li>According to the two histograms, the <strong>bootstrap distribution
of the sample mean</strong> is <strong>approximately
normal</strong>.</li>
<li>With mean 20.9, it is centered at approximately at the same location
as the original mean, 20.9</li>
<li>We get a rough idea of the amount of variability.
<ul>
<li>We can quantify the variability by computing the **standard
deviation of the bootstrap distribution, 1.31 in this case.</li>
<li>This is called the <strong>bootstrap standard error</strong>.</li>
</ul></li>
<li>The standard deviation of the data is 6.66, while the bootstrap
standard error is samller.
<ul>
<li>This reflects the fact that an average of 25 observations is more
accurate (less variable) than a single observation.</li>
</ul></li>
</ul>
<p><br></p>
<blockquote>
<ul>
<li>The sample mean, <span class="math inline">\(\bar{x}\)</span> gives
an estimate of the true(population) mean <span
class="math inline">\(\mu\)</span>, but its probability does not hit it
exactly.
<ul>
<li>Thus, it would be nice to have **a range of value for the <span
class="math inline">\(\mu\)</span> that we are 95% sure includes the
true(population) mean, <span class="math inline">\(\mu\)</span>.</li>
</ul></li>
</ul>
</blockquote>
<p><br></p>
<ul>
<li>In urine concentration levels 1-hour after the ingestion of Aspirin
A, we saw how the sample means vary for samples of size 50.
<ul>
<li>If most of the sample means are concentrated within a certain
interval of the bootstrap distribution, it seems reasonable to assume
that the true(population) mean is most likely somewhere in the same
interval.</li>
<li>Thus, we can construct a 90% CI by using the 5.0 and 95.0
percentiles of the bootstrap distribution as endpoints.</li>
<li>And the conclusion would be: <strong>we are 90% confident that the
true mean lies within this interval</strong>. These are called
<strong>bootstrap percentile confidence interval</strong></li>
</ul></li>
</ul>
<p><br></p>
<blockquote>
<p><strong>Bootstrap Percentile Confidence Intervals</strong></p>
<ul>
<li>The interval between <span class="math inline">\(\alpha /2\)</span>
and <span class="math inline">\(1-\alpha/2\)</span> quantiles of the
bootstrap distribution of a statistic is a <span
class="math inline">\((1-\alpha) \times 100\)</span> bootstrap
percentile confidence interval (CI) for the corresponding
parameter.</li>
</ul>
</blockquote>
<pre class="r"><code># Bootstrap percentile confidence interval
(lb &lt;- quantile(xbar, 0.05) %&gt;% round(1)) #18.8</code></pre>
<pre><code>##   5% 
## 18.8</code></pre>
<pre class="r"><code>(ub &lt;- quantile(xbar, 0.95) %&gt;% round(1)) #23.1</code></pre>
<pre><code>##  95% 
## 23.1</code></pre>
<pre class="r"><code># Point Estimate of the mean concentration level
mean(xbar) %&gt;% round(1)</code></pre>
<pre><code>## [1] 21</code></pre>
<pre class="r"><code># Mean of the original sample
mean(aspirinPharm$Avals) %&gt;% round(1)</code></pre>
<pre><code>## [1] 20.9</code></pre>
<p><br><br></p>
</div>
</div>
<div id="direct-comoputation-boot-and-boot.ci" class="section level3">
<h3>3. Direct Comoputation: <code>boot()</code> and
<code>boot.ci()</code></h3>
<ul>
<li>Compute the confidence interval ‘<strong>directly</strong>’ using
the <code>R</code> function <code>boot</code> and <code>boot.ci</code>.
<ul>
<li>Use <code>boot()</code> to save the output and then</li>
<li>Use <code>boot.ci()</code> with the object created by
<code>boot()</code> called <code>bootObj</code></li>
</ul></li>
<li>Set the <span class="math inline">\(B=10000\)</span>.</li>
<li>We will get estimates for both the <strong>sample mean</strong> and
<strong>sample standard deviation</strong>.</li>
</ul>
<pre class="r"><code>library(boot)
xbarStats &lt;- function(x, idx) {
    return(c(mean(x[idx]), var(x[idx])))
    }

(bootObj &lt;- boot(aspirinPharm$Avals, xbarStats, 10000))</code></pre>
<pre><code>## 
## ORDINARY NONPARAMETRIC BOOTSTRAP
## 
## 
## Call:
## boot(data = aspirinPharm$Avals, statistic = xbarStats, R = 10000)
## 
## 
## Bootstrap Statistics :
##     original     bias    std. error
## t1*  20.9320 -0.0087108    1.298596
## t2*  44.3556 -1.7618981   10.924173</code></pre>
<ul>
<li>To get the 90% confidence interval, use <code>boot.ci()</code>.</li>
</ul>
<pre class="r"><code>(aCI &lt;- boot.ci(bootObj, conf = 0.9))</code></pre>
<pre><code>## BOOTSTRAP CONFIDENCE INTERVAL CALCULATIONS
## Based on 10000 bootstrap replicates
## 
## CALL : 
## boot.ci(boot.out = bootObj, conf = 0.9)
## 
## Intervals : 
## Level      Normal              Basic             Studentized     
## 90%   (18.80, 23.08 )   (18.78, 23.08 )   (18.69, 23.26 )  
## 
## Level     Percentile            BCa          
## 90%   (18.79, 23.09 )   (18.84, 23.13 )  
## Calculations and Intervals on Original Scale</code></pre>
<ul>
<li>Here we use the <code>Percentile</code> confidence intervals.</li>
<li>Thus, we can get the <strong>point estimate</strong> from the output
of <code>boot()</code>, which we saved in <code>bootObj</code>.
<ul>
<li>the value in [t1*, original], 20.9320, is the point estimate.</li>
</ul></li>
<li>The corresponding 90% confidence interval is from
<code>boot.ci()</code> and is 18.79 to 23.09.</li>
</ul>
<p><br><br></p>
</div>
<div id="paired-data" class="section level3">
<h3>4. Paired data</h3>
<ul>
<li>In our pharmacology example, the question is **whether aspirin A or
aspirin B results in higher urine concentrations 1-hour after ingestion
on average.</li>
<li>What is of interest is in <strong>determining whether the mean urine
levels differ between the two aspirins</strong>.</li>
<li>Since each patient had ingested both aspirin A and B, we need to
account for this <strong>natural pairing</strong>.</li>
</ul>
<p><br></p>
<ul>
<li>distribution of the data</li>
</ul>
<pre class="r"><code>boxplot(list(aspirinPharm$Avals, aspirinPharm$Bvals),
        ylab = &quot;Concentration in Urine&quot;,
        xlab = &quot;aspirin type&quot;,
        col = c(&quot;lemonchiffon&quot;,&quot;salmon&quot;),
        names=c(&quot;Aspirin A&quot;,&quot;Aspirin B&quot;))</code></pre>
<p><img src="stat_seminar_wk05-1_files/figure-html/unnamed-chunk-12-1.png" width="672" /></p>
<p><br></p>
<div
id="determine-the-approximate-sampling-distribution-for-the-difference-in-means"
class="section level4">
<h4>4.1 Determine the (approximate) sampling distribution for the
difference in means</h4>
<ul>
<li>‘manual’ bootstrapping</li>
<li>Since we want to take care of the <strong>natural pairing</strong>
of the data so for each patient,
<ul>
<li>we will take <strong>difference between the aspirin A concentration
levels and aspirin B concentration levels</strong>.</li>
<li>Then we will perform a bootstrap on these computed differences.</li>
</ul></li>
</ul>
<pre class="r"><code>B &lt;- 10000
n &lt;- dim(aspirinPharm)[1]
diffs &lt;- aspirinPharm$Avals - aspirinPharm$Bvals
boot.diff &lt;- replicate(10000, 
                       {
                         x &lt;- sample(diffs, size = n, replace = T)
                         mean(x)
                        }
                       )</code></pre>
<ul>
<li>Check the approximate sampling distribution for the mean (paired)
differences.</li>
</ul>
<pre class="r"><code>hist(boot.diff, col = &quot;lemonchiffon&quot;, freq = F,
     xlab = &quot;sample mean difference&quot;, 
     ylab = &quot;probability&quot;, 
     main = &quot;Sample Mean Difference Distribution&quot;)
lines(density(boot.diff), col=6, lwd=3)</code></pre>
<p><img src="stat_seminar_wk05-1_files/figure-html/unnamed-chunk-14-1.png" width="672" /></p>
<ul>
<li>The <strong>sampling distribution of the mean differences</strong>
appears to be approximately normally distributed.</li>
<li>When generating the sampling distribution, we need to be careful
because <strong>the two variables are measured on the same observational
unit and are not on two independent samples</strong>
<ul>
<li>Bootstrap procedure needs to mimic the actual data collection
process.</li>
<li>However, paired data is not independent with each other.</li>
<li>Thus, when we compare paired data such as this example, we
<strong>compute the difference (or whatever value of interest) for each
observation first</strong>.</li>
<li>As a result, we will <strong>have one variable of interest</strong>.
Then we can proceed with the bootstrap procedure as a single variable
case.</li>
</ul></li>
</ul>
<p><br><br></p>
</div>
<div id="answer" class="section level4">
<h4>4.2 Answer</h4>
<ul>
<li>Question: is there a difference in the mean concentration level in
the urine 1-hour after the aspirin was ingested between Aspirin A and B?
(Use a 95% confidence interval)</li>
</ul>
<p><br></p>
<ul>
<li>will use <strong>approximate sampling distribution</strong></li>
<li>The point estimate of the difference of the aspirin A and the
aspirin B is:
<ul>
<li>Keep in mind that the point estimate is still computed based on the
sample (NOT from the bootstrapped sampling distribution)</li>
</ul></li>
</ul>
<pre class="r"><code>mean(aspirinPharm$Avals - aspirinPharm$Bvals) %&gt;% round(1)</code></pre>
<pre><code>## [1] -0.5</code></pre>
<ul>
<li>The 95% confidence interval is computed by using the
<code>quantile()</code> function from the bootstrapped sampling
distribution.</li>
</ul>
<pre class="r"><code>(lb &lt;- quantile(boot.diff, 0.025) %&gt;% round(1))</code></pre>
<pre><code>## 2.5% 
## -3.9</code></pre>
<pre class="r"><code>(ub &lt;- quantile(boot.diff, 0.975) %&gt;% round(1))</code></pre>
<pre><code>## 97.5% 
##   2.9</code></pre>
<ul>
<li>Conclusion: the 95% confidence interval is -3.9 to 2.9. Since the
interval contains 0, there is no evidence that there is a difference in
the mean concentration levels in urine 1-hour post ingestion of the
aspirin.</li>
</ul>
<p><br></p>
</div>
<div id="direct-method-boot-and-boot.ci" class="section level4">
<h4>4.3 Direct method: <code>boot()</code> and
<code>boot.ci()</code></h4>
<pre class="r"><code>xbar.Diffs &lt;- function(x, idx) {
    return(c(mean(x[idx]), var(x[idx]))) 
}

(diffs.bootObj &lt;- boot(diffs, xbar.Diffs, 10000))</code></pre>
<pre><code>## 
## ORDINARY NONPARAMETRIC BOOTSTRAP
## 
## 
## Call:
## boot(data = diffs, statistic = xbar.Diffs, R = 10000)
## 
## 
## Bootstrap Statistics :
##     original     bias    std. error
## t1*  -0.4680  0.0300408     1.76825
## t2*  81.6556 -3.5840770    23.71024</code></pre>
<pre class="r"><code># point estimate
diffs.bootObj$t0[1] %&gt;% round(1)</code></pre>
<pre><code>## [1] -0.5</code></pre>
<ul>
<li>The point estimate is [t1*, original], -0.5.</li>
</ul>
<pre class="r"><code>diffCI &lt;- boot.ci(diffs.bootObj, conf = 0.95)

# Percentile method CI
diffCI$percent[4] %&gt;% round(3)</code></pre>
<pre><code>## [1] -3.896</code></pre>
<pre class="r"><code>diffCI$percent[5] %&gt;% round(3)</code></pre>
<pre><code>## [1] 2.996</code></pre>
<ul>
<li>Conclusion: the point estimate for the mean difference in
concentration levels in the urine between aspirin A and aspirin B 1-hour
post-ingestion is [t1*, original], -0.5 (from the original data, not
from the bootstrapped sampling distribution). The corresponding 95%
confidence interval is -3.896 to 2.996.</li>
</ul>
<p><br><br></p>
</div>
</div>
<div id="bootstrap-hypothesis-testing" class="section level3">
<h3>5. Bootstrap hypothesis testing</h3>
<ul>
<li>Bootstrap hypothesis testing is relatively undeveloped, and is
generally <strong>not used as much as another approach we will learn
later(permutation test)</strong>.</li>
<li>However, there are some ways to do bootstrap tests.
<ul>
<li>&lt;1&gt; One general approximate approach is to base a test on a
bootstrap confidence interval
<ul>
<li>To reject the <span class="math inline">\(H_0\)</span> null
hypothesis if the interval fails to inlcude <span
class="math inline">\(\theta_0\)</span>.</li>
</ul></li>
<li>&lt;2&gt; Anoother general approach is to sample in a way that is
consistent with the null hypothesis, then calculate a <span
class="math inline">\(p\)</span>-value as a tail probability like we do
in <strong>permutation tests</strong>.
<ul>
<li>One naive way to do this is to modify the observations, e.g. to
subtract the difference between the observed statistical value from the
sample (<span class="math inline">\(\hat{\theta}\)</span>) and the null
hypothesis value for the parameter (<span
class="math inline">\(\theta_0\)</span>) each observation.</li>
<li>In other words, in the original sample, we would substract the value
<span class="math inline">\(\hat{\theta}-\theta_0\)</span> from each
observation and then do the bootstrap on these modified values.</li>
<li>However, this is not highly recommended because
<ul>
<li>it is not accurate for skewed populations,</li>
<li>it can give impossible data (e.g. negative time measurements),
and</li>
<li>it does not generalize well to other applications such as relative
risk, correlation, regression, or categorical data.</li>
</ul></li>
</ul></li>
</ul></li>
</ul>
<p><br></p>
<ul>
<li>We will just base a test on a bootstrap confidence interval to
reject the null hypothesis.</li>
<li>Specifically, if the significance level is <span
class="math inline">\(\alpha\)</span>, we would use a <span
class="math inline">\((1-\alpha) \times 100\)</span>% confidence
interval to <strong>determine whether we would reject the null
hypothesis or not</strong>.</li>
</ul>
<p><br><br><br></p>
<p><a href="toc.html">&lt; Back to Syllabus</a></p>
<p><br><br><br></p>
</div>

<br><br>
<footer>
  <p class="copyright text-muted" align="center">Copyright &copy; 2024 Cold Spring Harbor Laboratory</p>
</footer>


</div>
</div>

</div>

<script>

// add bootstrap table styles to pandoc tables
function bootstrapStylePandocTables() {
  $('tr.odd').parent('tbody').parent('table').addClass('table table-condensed');
}
$(document).ready(function () {
  bootstrapStylePandocTables();
});


</script>

<!-- tabsets -->

<script>
$(document).ready(function () {
  window.buildTabsets("TOC");
});

$(document).ready(function () {
  $('.tabset-dropdown > .nav-tabs > li').click(function () {
    $(this).parent().toggleClass('nav-tabs-open');
  });
});
</script>

<!-- code folding -->

<script>
$(document).ready(function ()  {

    // temporarily add toc-ignore selector to headers for the consistency with Pandoc
    $('.unlisted.unnumbered').addClass('toc-ignore')

    // move toc-ignore selectors from section div to header
    $('div.section.toc-ignore')
        .removeClass('toc-ignore')
        .children('h1,h2,h3,h4,h5').addClass('toc-ignore');

    // establish options
    var options = {
      selectors: "h1,h2,h3,h4",
      theme: "bootstrap3",
      context: '.toc-content',
      hashGenerator: function (text) {
        return text.replace(/[.\\/?&!#<>]/g, '').replace(/\s/g, '_');
      },
      ignoreSelector: ".toc-ignore",
      scrollTo: 0
    };
    options.showAndHide = false;
    options.smoothScroll = false;

    // tocify
    var toc = $("#TOC").tocify(options).data("toc-tocify");
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    script.src  = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML";
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>

</body>
</html>
