<!DOCTYPE html>

<html>

<head>

<meta charset="utf-8" />
<meta name="generator" content="pandoc" />
<meta http-equiv="X-UA-Compatible" content="IE=EDGE" />




<title>Week 3-2. Hypothesis testing for a population proportion</title>

<script src="site_libs/header-attrs-2.16/header-attrs.js"></script>
<script src="site_libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<meta name="viewport" content="width=device-width, initial-scale=1" />
<link href="site_libs/bootstrap-3.3.5/css/cosmo.min.css" rel="stylesheet" />
<script src="site_libs/bootstrap-3.3.5/js/bootstrap.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/html5shiv.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/respond.min.js"></script>
<style>h1 {font-size: 34px;}
       h1.title {font-size: 38px;}
       h2 {font-size: 30px;}
       h3 {font-size: 24px;}
       h4 {font-size: 18px;}
       h5 {font-size: 16px;}
       h6 {font-size: 12px;}
       code {color: inherit; background-color: rgba(0, 0, 0, 0.04);}
       pre:not([class]) { background-color: white }</style>
<script src="site_libs/jqueryui-1.11.4/jquery-ui.min.js"></script>
<link href="site_libs/tocify-1.9.1/jquery.tocify.css" rel="stylesheet" />
<script src="site_libs/tocify-1.9.1/jquery.tocify.js"></script>
<script src="site_libs/navigation-1.1/tabsets.js"></script>
<link href="site_libs/highlightjs-9.12.0/default.css" rel="stylesheet" />
<script src="site_libs/highlightjs-9.12.0/highlight.js"></script>
<link href="site_libs/font-awesome-5.1.0/css/all.css" rel="stylesheet" />
<link href="site_libs/font-awesome-5.1.0/css/v4-shims.css" rel="stylesheet" />

<style type="text/css">
  code{white-space: pre-wrap;}
  span.smallcaps{font-variant: small-caps;}
  span.underline{text-decoration: underline;}
  div.column{display: inline-block; vertical-align: top; width: 50%;}
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
  ul.task-list{list-style: none;}
    </style>

<style type="text/css">code{white-space: pre;}</style>
<script type="text/javascript">
if (window.hljs) {
  hljs.configure({languages: []});
  hljs.initHighlightingOnLoad();
  if (document.readyState && document.readyState === "complete") {
    window.setTimeout(function() { hljs.initHighlighting(); }, 0);
  }
}
</script>






<link rel="stylesheet" href="styles.css" type="text/css" />



<style type = "text/css">
.main-container {
  max-width: 940px;
  margin-left: auto;
  margin-right: auto;
}
img {
  max-width:100%;
}
.tabbed-pane {
  padding-top: 12px;
}
.html-widget {
  margin-bottom: 20px;
}
button.code-folding-btn:focus {
  outline: none;
}
summary {
  display: list-item;
}
details > summary > p:only-child {
  display: inline;
}
pre code {
  padding: 0;
}
</style>


<style type="text/css">
.dropdown-submenu {
  position: relative;
}
.dropdown-submenu>.dropdown-menu {
  top: 0;
  left: 100%;
  margin-top: -6px;
  margin-left: -1px;
  border-radius: 0 6px 6px 6px;
}
.dropdown-submenu:hover>.dropdown-menu {
  display: block;
}
.dropdown-submenu>a:after {
  display: block;
  content: " ";
  float: right;
  width: 0;
  height: 0;
  border-color: transparent;
  border-style: solid;
  border-width: 5px 0 5px 5px;
  border-left-color: #cccccc;
  margin-top: 5px;
  margin-right: -10px;
}
.dropdown-submenu:hover>a:after {
  border-left-color: #adb5bd;
}
.dropdown-submenu.pull-left {
  float: none;
}
.dropdown-submenu.pull-left>.dropdown-menu {
  left: -100%;
  margin-left: 10px;
  border-radius: 6px 0 6px 6px;
}
</style>

<script type="text/javascript">
// manage active state of menu based on current page
$(document).ready(function () {
  // active menu anchor
  href = window.location.pathname
  href = href.substr(href.lastIndexOf('/') + 1)
  if (href === "")
    href = "index.html";
  var menuAnchor = $('a[href="' + href + '"]');

  // mark the anchor link active (and if it's in a dropdown, also mark that active)
  var dropdown = menuAnchor.closest('li.dropdown');
  if (window.bootstrap) { // Bootstrap 4+
    menuAnchor.addClass('active');
    dropdown.find('> .dropdown-toggle').addClass('active');
  } else { // Bootstrap 3
    menuAnchor.parent().addClass('active');
    dropdown.addClass('active');
  }

  // Navbar adjustments
  var navHeight = $(".navbar").first().height() + 15;
  var style = document.createElement('style');
  var pt = "padding-top: " + navHeight + "px; ";
  var mt = "margin-top: -" + navHeight + "px; ";
  var css = "";
  // offset scroll position for anchor links (for fixed navbar)
  for (var i = 1; i <= 6; i++) {
    css += ".section h" + i + "{ " + pt + mt + "}\n";
  }
  style.innerHTML = "body {" + pt + "padding-bottom: 40px; }\n" + css;
  document.head.appendChild(style);
});
</script>

<!-- tabsets -->

<style type="text/css">
.tabset-dropdown > .nav-tabs {
  display: inline-table;
  max-height: 500px;
  min-height: 44px;
  overflow-y: auto;
  border: 1px solid #ddd;
  border-radius: 4px;
}

.tabset-dropdown > .nav-tabs > li.active:before {
  content: "";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li.active:before {
  content: "&#xe258;";
  border: none;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open:before {
  content: "";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs > li.active {
  display: block;
}

.tabset-dropdown > .nav-tabs > li > a,
.tabset-dropdown > .nav-tabs > li > a:focus,
.tabset-dropdown > .nav-tabs > li > a:hover {
  border: none;
  display: inline-block;
  border-radius: 4px;
  background-color: transparent;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li {
  display: block;
  float: none;
}

.tabset-dropdown > .nav-tabs > li {
  display: none;
}
</style>

<!-- code folding -->



<style type="text/css">

#TOC {
  margin: 25px 0px 20px 0px;
}
@media (max-width: 768px) {
#TOC {
  position: relative;
  width: 100%;
}
}

@media print {
.toc-content {
  /* see https://github.com/w3c/csswg-drafts/issues/4434 */
  float: right;
}
}

.toc-content {
  padding-left: 30px;
  padding-right: 40px;
}

div.main-container {
  max-width: 1200px;
}

div.tocify {
  width: 20%;
  max-width: 260px;
  max-height: 85%;
}

@media (min-width: 768px) and (max-width: 991px) {
  div.tocify {
    width: 25%;
  }
}

@media (max-width: 767px) {
  div.tocify {
    width: 100%;
    max-width: none;
  }
}

.tocify ul, .tocify li {
  line-height: 20px;
}

.tocify-subheader .tocify-item {
  font-size: 0.90em;
}

.tocify .list-group-item {
  border-radius: 0px;
}

.tocify-subheader {
  display: inline;
}
.tocify-subheader .tocify-item {
  font-size: 0.95em;
}

</style>



</head>

<body>


<div class="container-fluid main-container">


<!-- setup 3col/9col grid for toc_float and main content  -->
<div class="row">
<div class="col-xs-12 col-sm-4 col-md-3">
<div id="TOC" class="tocify">
</div>
</div>

<div class="toc-content col-xs-12 col-sm-8 col-md-9">




<div class="navbar navbar-default  navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-bs-toggle="collapse" data-target="#navbar" data-bs-target="#navbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="index.html">Cold Spring Harbor Laboratory Biostatistics</a>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
    Services
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
    <li>
      <a href="services.html">Basic Services</a>
    </li>
    <li>
      <a href="grant_application.html">Grant Application Help</a>
    </li>
  </ul>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
    Training
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
    <li>
      <a href="biostatistics_course.html">Biostatistics Course (Summer)</a>
    </li>
    <li>
      <a href="toc.html">Intro to Biostatistics with R</a>
    </li>
  </ul>
</li>
<li>
  <a href="https://github.com/taehoonh/CSHLbiostat">
    <span class="fa fa-github"></span>
     
  </a>
</li>
      </ul>
    </div><!--/.nav-collapse -->
  </div><!--/.container -->
</div><!--/.navbar -->

<div id="header">




</div>


<!-- <link rel="stylesheet" href="styles.css" type="text/css"> -->
<p><br><br><br></p>
<p><a href="toc.html">&lt; Back to Syllabus</a></p>
<p><br><br><br></p>
<div id="todays-data" class="section level3">
<h3>1. Today’s data</h3>
<ul>
<li><p>There was a study to compare the proportion of patients who were
not abusing substances one year after the end of a treatment program.
Nationwide, it is known that the rate of relapse after completing a
substance abuse program is 50%. A team of researchers has tested a new
substance abuse treatment program and found that at one year after the
completion of the program, 31 of the individuals out of 50 that were
treated were not abusing substances. The researchers want to know
whether their treatment program appears better than the existing
programs.</p></li>
<li><p>If the new treatment were not better than the existing
treatments, the researchers would have expected 50% of the patients to
have relapsed by one year post treatment.</p>
<ul>
<li>Our estimate for the success of the new program would be <span
class="math inline">\(p = 31/50 = 0.62\)</span>.</li>
<li>Is this value far enough from 0.50 to indicate that the new
treatment works better than the available treatments?</li>
</ul></li>
<li><p>We can answer this by calculating a <strong>confidence
interval</strong> (perhaps a 95% confidence interval) for the population
proportion, <span class="math inline">\(\pi\)</span>, and determining
whether the interval contains 0.50.</p>
<ul>
<li>If the interval contains 0.50, we would have no evidence that this
treatment works because random variability from sample to sample could
explain why we got 0.62 when in reality the population proportion is
equal to 0.50. We could also use another approach.</li>
</ul></li>
</ul>
<p><br><br></p>
</div>
<div id="sampling-distribution-of-the-sample-proportion"
class="section level3">
<h3>2. Sampling distribution of the sample proportion</h3>
<ul>
<li>Sample proportion, <span class="math inline">\(P=Y/n\)</span> is a
random variable.</li>
<li>It is a rescaling of the binomial random variable <span
class="math inline">\(Y∼B(n, \pi)\)</span>.</li>
<li>If the treatment had the same success of preventing relapse to
substance abuse within one year of the completion of treatment, the
number of patients who did not relapse, <span
class="math inline">\(Y\)</span> would have a binomial distribution,
<span class="math inline">\(Y∼B(50, 0.5)\)</span>.</li>
<li>The sampling distribution for the sample proportion <span
class="math inline">\(P\)</span> is rescaling of the distribution of
<span class="math inline">\(Y\)</span> by dividing <span
class="math inline">\(Y\)</span> by 50 (or by multiplying <span
class="math inline">\(Y\)</span> by 1/50 ).</li>
</ul>
<p><br><br></p>
<div id="simulation-of-the-sampling-proportion" class="section level4">
<h4>2.1 Simulation of the sampling proportion</h4>
<ul>
<li>Use <code>rbinom()</code>.</li>
<li>Sampling distribution with 5000 repeats of obtaining a random sample
of 50 patients who are treated with standard treatment for substance
abuse (so with <span class="math inline">\(\pi\)</span> for probability
of no relapse within one year of completing treatment).</li>
<li>Create vector of 5000 sample proportions determined from a random
sample of 50 individuals from a population with a probability of
success, 0.50.</li>
</ul>
<pre class="r"><code>sampProps &lt;- rbinom(5000, size = 50, prob = 0.5) / 50</code></pre>
<ul>
<li>Plot this data and indicate where our observed sample proportion of
0.62, lies within this sampling distribution.</li>
</ul>
<pre class="r"><code>hist(sampProps, 
     xlab = &quot;proportion of patients who did not relapse&quot;,
     ylab = &quot;probability&quot;,
     main = &quot;PMF for proportion of patients who did not relapse&quot;)

abline(v = 0.62, col = 2, lwd = 4)</code></pre>
<p><img src="stat_seminar_wk03-2_files/figure-html/unnamed-chunk-3-1.png" width="672" /></p>
<ul>
<li>The researchers claim that their treatment program for substance
abuse is better than standard treatment programs.
<ul>
<li>Evidence that supports their claim would be values of the sample
proportion that are greater than 0.50.</li>
<li>So looking at the plot above, this would be the values of 0.62 and
the probability of getting a value of 0.62 or more is shaded in the
histogram.</li>
</ul></li>
</ul>
<pre class="r"><code>h &lt;- hist(sampProps, breaks = 20, plot = FALSE)
ccat &lt;- cut(h$breaks, c(-Inf, 0.61, Inf))

plot(h, col = c(&quot;white&quot;, &quot;indianred&quot;)[ccat],
     xlab = &quot;proportion of patients who did not relapse&quot;, 
     ylab = &quot;probability&quot;, 
     main = &quot;PMF for proportion of patients who did not relapse&quot;)
abline(v = 0.62, col = 2, lwd = 4)</code></pre>
<p><img src="stat_seminar_wk03-2_files/figure-html/unnamed-chunk-4-1.png" width="672" /></p>
<ul>
<li>The probability of the area above can be calculated:</li>
</ul>
<p><span class="math display">\[
p \text {-value }=\operatorname{Pr}(T \geq t)=1-F(t)
\]</span></p>
<ul>
<li><code>R</code></li>
</ul>
<pre class="r"><code>(result &lt;- 1 - pbinom(30, 50, 0.5) %&gt;% round(3))</code></pre>
<pre><code>## [1] 0.059</code></pre>
<ul>
<li>The probability that the researchers would observe a sample
proportion of 0.62 or greater if their treatment only worked as well as
standard treatments is 0.059. At this point, there are two choices:
<ul>
<li>OPTION 1. The new treatment works as well as the standard treatment
and the researchers got a relatively unlikely result (i.e. one that
would happen 0.059 of the time).</li>
<li>OPTION 2. The assumption that the new treatment has the same success
rate as the standard treatment is not correct.</li>
</ul></li>
<li>Different people may arrive at different conclusions.
<ul>
<li>The chance of getting a sample proportion of 0.059 if the new
treatment had the same success rate as standard therapy would happen 6
in 100 times.</li>
<li>Some people would think that is a relatively rare event and so would
be likely to believe OPTION 2 and conclude that the new treatment has a
better success rate than the standard treatments.</li>
<li>Other people may believe that there is not enough information to
conclude that the new treatment has a better success rate than standard
treatment.</li>
</ul></li>
<li>Can use this approach to <strong>determine whether there is evidence
to support scientific claims</strong>.
<ul>
<li>Specifically, (1) can determine the sampling distribution of the
sample statistic under a reasonable assumption and</li>
<li><ol start="2" style="list-style-type: decimal">
<li>can determine whether there is evidence that the sample proportion
we obtained is unusual or not under our assumption.</li>
</ol></li>
</ul></li>
</ul>
<p><br><br></p>
</div>
</div>
<div id="hypothesis-testing" class="section level3">
<h3>3. Hypothesis testing</h3>
<ul>
<li>Key concepts:
<ul>
<li><strong>Hypothesis testing</strong>: a formal statistical procedure
that quantifies the evidence that supports one of two mutually exclusive
hypotheses.</li>
<li><strong>Null hypothesis</strong> (i.e., <span
class="math inline">\(H_0\)</span>): represents the <strong>status
quo</strong>, or the expected result.
<ul>
<li>Status quo depends on the experimental design.</li>
<li>(Single group) the status quo would be based on historical
values.</li>
<li>(Two groups) the status quo would be that the two groups are the
same.</li>
</ul></li>
<li><strong>Alternative hypothesis</strong> (i.e., <span
class="math inline">\(H_a\)</span>): represents the <strong>research
hypothesis</strong>, what we really believe is true.</li>
<li><strong>Test statistic</strong>: a numercial measure of computing
the effect of interests.</li>
<li><strong>Significance level</strong>: the amount of confidence that
we have in concluding that the effect is not solely driven by
chance.</li>
</ul></li>
</ul>
<p><br></p>
<div id="test-statistic" class="section level4">
<h4>3.1 Test statistic</h4>
<ul>
<li><strong>Test statistic</strong>: a <strong>function</strong> of the
data whose value determines the result of the test. Test statistic is a
random variable.
<ul>
<li>Denote with <span class="math inline">\(X_1, ..., X_n\)</span>, a
simple random sample from a distribution <span
class="math inline">\(F_{\theta}\)</span>.</li>
<li>The function <span class="math inline">\(T(X_1, ..., X_n)\)</span>
is <strong>test statistic</strong>.</li>
</ul></li>
</ul>
<p><br></p>
</div>
<div id="the-null-distribution" class="section level4">
<h4>3.2 The null distribution</h4>
<ul>
<li><strong>Null distribution</strong>: the distribution of the test
statistic <strong>if the null hypothesis is true</strong>.</li>
<li>Can think of the null distribution as the reference distribution: we
determine where the observed value of the test statistic is within the
sampling distribution <strong>under the null hypothesis</strong>.</li>
</ul>
<p><br></p>
</div>
<div id="p-value" class="section level4">
<h4>3.3 <span class="math inline">\(p\)</span>-value</h4>
<ul>
<li>the probability under the null hypothesis of observing a value as
unlikely or more unlikely than the value observed for the test statistic
based on sample.</li>
<li>a measure of the <strong>distance from the observed statistic to the
value of the parameter</strong> specified by the null hypothesis.</li>
<li>the probability that chance alone would produce a test statistic as
extreme as the one observed.</li>
<li>(For <span class="math inline">\(p\)</span>-value calculation) need
to know (or estimate) the CDF of the test statistic under the null
distribution.</li>
</ul>
<p><br></p>
<blockquote>
<p><span class="math inline">\(p\)</span>-value is NOT the probability
that the null hypothesis is true.</p>
</blockquote>
<p><br></p>
</div>
<div id="significance-level" class="section level4">
<h4>3.4 Significance level</h4>
<ul>
<li>We define a result as <strong>statistically significant</strong> if
the value of the test statistic is unlikely to occur by chance if the
null hypothesis is true.
<ul>
<li>“unlikely” can be defined as significance level, <span
class="math inline">\(\alpha\)</span>.</li>
</ul></li>
<li>Should be set a <strong>priori</strong> meaning at the time the
study is designed.</li>
<li>Common expression: “a result is statistically significant at level
<span class="math inline">\(\alpha\)</span> if the <span
class="math inline">\(p\)</span>-value is such that <span
class="math inline">\(p\)</span>-value &lt; <span
class="math inline">\(\alpha\)</span>”</li>
</ul>
<p><br></p>
</div>
<div id="steps-of-hypothesis-testing" class="section level4">
<h4>3.5 Steps of Hypothesis Testing</h4>
<ul>
<li>&lt;1&gt; Decide on the effect that you want to study. Select a
suitable test statistic to measure the effect.</li>
<li>&lt;2&gt; Set up a null hypothesis, which is a simple, tractable
model that allows you to comput the null distribution.</li>
<li>&lt;3&gt; State the alternative hypothesis. This will be either
one-sided or two-sided.</li>
<li>&lt;4&gt; Do the experiment, collect the data, and compute the
observed value of the test statistic.</li>
<li>&lt;5&gt; Make a decision: reject the null hypothesis if the <span
class="math inline">\(p\)</span>-value &lt; <span
class="math inline">\(\alpha\)</span>, significance level.</li>
<li>&lt;6&gt; Write a conclusion using words in context of the study
that generated the data. This should contain an indication of whether
the result is statistically significant (report a <span
class="math inline">\(p\)</span>-value) and should give an estimate of
the result (including a confidence interval).</li>
</ul>
<p><br><br></p>
</div>
</div>
<div id="hypothesis-test-example" class="section level3">
<h3>4. Hypothesis test example</h3>
<ul>
<li>The researchers want to know if their substance abuse treatment
program has a greater proportion of patient who do not relapse within
the ﬁrst year after the completion of treatment than the currently
available standard treatment.
<ul>
<li><span class="math inline">\(\alpha\)</span>=0.05</li>
<li><span class="math inline">\(H_0: \pi=0.5\)</span>
<ul>
<li>This is the null hypothesis because the status quo is the currently
used standard treatment program it has a historical value of the
proportion of patients who do not relapse within the first year of
treatment of 0.50.</li>
</ul></li>
<li><span class="math inline">\(H_a: \pi&gt;0.5\)</span>
<ul>
<li>This is the alternative hypothesis because the researchers believe
that their new treatment program is better than currently used
standard.</li>
<li>The new treatment program would be deemed better if the proportion
of patient who do not relapse within the first year after the completion
of treatment is greater than the proportion for the current standard
treatment.</li>
</ul></li>
<li>estimator for the population proportion, <span
class="math inline">\(\pi\)</span> is the sample proportion and that its
sampling distribution is a rescaled binomial PMF.</li>
<li>Test-statistic: <span class="math inline">\(T(Y)=Y/50\)</span></li>
<li>Observed value of the statistic is <span
class="math inline">\(t=0.62\)</span>.</li>
<li><span class="math inline">\(T\)</span> has a rescaled binomial PMF
and, under <span class="math inline">\(H_0\)</span>, <span
class="math inline">\(\pi=0.5\)</span>, the null distribution of the
test staistic is a rescaled <span class="math inline">\(B(50,
0.5)\)</span> PMF with a rescaling value of <span
class="math inline">\(1/50\)</span> (meaning we divide the binomial
random variable <span class="math inline">\(Y\)</span>, by 50).</li>
<li>Since it’s one-sided test and the researchers want to reject <span
class="math inline">\(H_0\)</span> if <span
class="math inline">\(\pi&gt;0.5\)</span>.</li>
<li><span class="math inline">\(p\)</span>-value = Pr<span
class="math inline">\((T \ge t)\)</span> = 1 - <span
class="math inline">\(F\)</span>(<span
class="math inline">\(t\)</span>), where F() is the CDF of the rescaled
binomial distribution.
<ul>
<li><span class="math inline">\(p\)</span>-value can be calculated by
using <code>pbinom()</code> in <code>R</code>.</li>
<li>Pr<span class="math inline">\((Y \ge 31)\)</span> = 1-Pr<span
class="math inline">\((Y&lt;31)\)</span> = 1-Pr<span
class="math inline">\((Y \le 31)\)</span></li>
</ul></li>
</ul></li>
</ul>
<pre class="r"><code>(result &lt;- 1 - pbinom(30, 50, 0.5) %&gt;% round(3))</code></pre>
<pre><code>## [1] 0.059</code></pre>
<ul>
<li>In this case, <span class="math inline">\(p\)</span>-value = 0.059
is greater than the significance level, <span
class="math inline">\(\alpha=0.05\)</span>.</li>
<li>We do not have enough evidence to reject the null hypotehsis <span
class="math inline">\(H_0\)</span>.</li>
<li>Conclusion: there is no evidence that the proportion of patients who
do not relapse within the first year after treatment completion with the
new treatment program differs from 0.50 (or is better than the standard
treatment program).</li>
</ul>
<pre class="r"><code>plot(0:50, dbinom(0:50, 50, 0.5), col=&quot;black&quot;, type = &quot;h&quot;, lwd = 2, xlab = &quot;T&quot;, ylab = &quot;PMF&quot;, main = &quot;P-value&quot;)
points(30:50, dbinom(30:50, 50, 0.5), type=&quot;h&quot;, lwd = 6, col = &quot;indianred&quot;)</code></pre>
<p><img src="stat_seminar_wk03-2_files/figure-html/unnamed-chunk-7-1.png" width="672" /></p>
<ul>
<li>The sum of the probabilities of the red region is the <span
class="math inline">\(p\)</span>-value.</li>
</ul>
<p><br><br></p>
</div>
<div id="key-points" class="section level3">
<h3>5. Key Points</h3>
<ul>
<li>(<span class="math inline">\(p\)</span>-value &lt; <span
class="math inline">\(\alpha\)</span>) the data show strong evidence
against the null hypothesis, hence we reject the null hypothesis.</li>
<li>(<span class="math inline">\(p\)</span>-value <span
class="math inline">\(\ge\)</span> <span
class="math inline">\(\alpha\)</span>) the data does NOT show strong
evidence against the null hypotehsis. The evidence is consistent with
the null hypothesis. Thus, we fail to reject the null hypothesis.</li>
</ul>
<p><br></p>
<blockquote>
<ul>
<li>Note that we never accept the null hypothesis. (There is no
guarantee that the null hypothesis is true!)</li>
<li>All we can conclude if <span class="math inline">\(p\)</span>-value
&gt; <span class="math inline">\(\alpha\)</span> is that <b>there is no
evidence to reject the null hypothesis in favor of the
alternative</b>.</li>
<li>This does not mean that there is evidence in favor of the null
hypothesis.</li>
<li>(<span class="math inline">\(p\)</span>-value &gt; <span
class="math inline">\(\alpha\)</span>) This does not mean the null
hypothesis is true. No evidence against the null hypothesis is not
evidence for the null hypothesis.</li>
</ul>
</blockquote>
<p><br><br></p>
</div>
<div id="why-do-we-do-an-indirect-test" class="section level3">
<h3>6. Why do we do an indirect test?</h3>
<ul>
<li><p>The problem is that if researchers believe that their treatment
for substance abuse is better than the standard treatment.</p></li>
<li><p>This means they believe that the proportion of patients who have
not relapsed within one year of treatment completion is greater than
0.5.</p></li>
<li><p>But to calculate a probability that this is true, based on our
test-statistic, we need to know the sampling distribution under this
hypothesis.</p></li>
<li><p>However, it is just stated that it is believed that the
population proportion, <span class="math inline">\(\pi\)</span> is
greater than 0.50 but no specivfic alue is given.</p></li>
<li><p>Hence, we do not know which rescaled binomial random variable and
distribution would be the one for the sampling distribution.</p></li>
<li><p>This is why we take in indirect approach.</p></li>
<li><p>If we assume the status quo, then we can compute the sampling
distribution if we believe the status quo (i.e., null hypothesis) is
true.</p></li>
<li><p>But that leaves us with the indirect approach: we assume the null
hypothesis is true and then assess the amount of evidence against this
assumption on the basis of a <span
class="math inline">\(p\)</span>-value.</p></li>
<li><p>If the <span class="math inline">\(p\)</span>-value is really
small, we can either believe:</p>
<ul>
<li>&lt;1&gt; we got an a rare or unusual sample, or</li>
<li>&lt;2&gt; the null hypothesis is not true.</li>
</ul></li>
<li><p>If the <span class="math inline">\(p\)</span>-value is “small
enough”, we conclude &lt;2&gt;, the null hypothesis is not true.</p>
<ul>
<li>“small enough” means level of significane, <span
class="math inline">\(\alpha\)</span>.</li>
</ul></li>
</ul>
<p><br></p>
<blockquote>
<p><strong>Court example</strong></p>
<ul>
<li><span class="math inline">\(H_0\)</span>: The person on trial is
innocent.</li>
<li><span class="math inline">\(H_a\)</span>: The prosecution believes
the person is guilty.</li>
<li>Data: The evidence is presented.</li>
<li>Reject <span class="math inline">\(H_0\)</span>: The jury will
convict if they believe the individual is guilty “beyond reasonable
doubt” which is <span class="math inline">\(p\)</span>-value &lt; <span
class="math inline">\(\alpha\)</span>.</li>
</ul>
</blockquote>
<p><br></p>
<div id="convention" class="section level4">
<h4>6.1 Convention</h4>
<ul>
<li>It is the convention in performing test of significance to do a
<strong>two-sided test</strong></li>
</ul>
<p><br></p>
</div>
<div id="p-value-and-confidence-interval" class="section level4">
<h4>6.2 <span class="math inline">\(p\)</span>-value and confidence
interval</h4>
<ul>
<li>It is usually expected that the significance level <span
class="math inline">\(\alpha\)</span> you use for hypothesis testing in
an analysis is the same one you use in computing a confidence
interval.</li>
<li>(One-sided test) you need to get the corresponding one-sided
confidence interval. There are two choices.
<ul>
<li>The population parameter is <strong>greater</strong> than what is
hypothesized in the null hypothesis. (i.e., <span
class="math inline">\(H_0: \pi&gt;0.5\)</span>)
<ul>
<li>CI: (0, Upper Limit)</li>
</ul></li>
<li>The population parameter is <strong>less</strong> than what is
hypothesized in the null hypothesis. (i.e., <span
class="math inline">\(H_0: \pi&lt;0.5\)</span>)
<ul>
<li>CI: (Lower Limit, 1)</li>
</ul></li>
</ul></li>
</ul>
<p><br></p>
<blockquote>
<ul>
<li>NEVER just report a <span class="math inline">\(p\)</span>-value
alone.</li>
<li>ALWAYS give the estimate of the population parameter and
corresponding confidence interval in addition.</li>
</ul>
</blockquote>
<p><br><br></p>
</div>
</div>
<div id="test-for-the-proportion-of-one-population-using-r"
class="section level3">
<h3>7. Test for the proportion of one population using
<code>R</code></h3>
<ul>
<li>Let <span class="math inline">\(Y\)</span> be a binomial random
variable, <span class="math inline">\(Y~B(n, \pi)\)</span>. Suppose that
we observe <span class="math inline">\(Y=y\)</span>. To test
<ul>
<li><span class="math inline">\(H_0: \pi= \pi_0\)</span></li>
<li><span class="math inline">\(H_a: \pi \ne \pi_0\)</span></li>
</ul></li>
<li>We compute the probability of observing a value as or more extreme
than the observed <span class="math inline">\(y\)</span>.</li>
<li>Also called as the <strong>Binomial test</strong>.</li>
</ul>
<p><br></p>
<div id="substance-abuse-treatment-program" class="section level4">
<h4>7.1 Substance abuse treatment program</h4>
<ul>
<li><code>R</code>: <code>binom.test()</code></li>
</ul>
<pre class="r"><code>binom.test(31, 50, p = 0.5, alternative = &#39;greater&#39;)</code></pre>
<pre><code>## 
##  Exact binomial test
## 
## data:  31 and 50
## number of successes = 31, number of trials = 50, p-value = 0.05946
## alternative hypothesis: true probability of success is greater than 0.5
## 95 percent confidence interval:
##  0.4939593 1.0000000
## sample estimates:
## probability of success 
##                   0.62</code></pre>
<p><br><br></p>
</div>
</div>
<div id="complete-example" class="section level3">
<h3>8. Complete example</h3>
<p>The goal was to lose at least 5 pounds by week 6 of the study. A
person was classified as ‘positive’ if s/he had lost 5 or more pounds by
week 6 of the or classified as ‘negative’ is s/he had not lost 5 pounds
by week 6. There were a total of 35 individuals enrolled on the study.
The data are in an Excel spreadsheet in a comma delimited format. You
are asked to analyze the data to determine whether the diet is
successful. The investigators would consider the diet to be successful
if more than 60% of the 35 individuals are considered ‘positive’ using a
significance level of <span class="math inline">\(\alpha\)</span> =
0.01. It is known that the best diet to date has a rate of 60% of
participants lose 5 pounds by week 6. For this study, patients were
weighed at baseline and then at week 6. If at week 6 an individual
weighed 5 or less pounds compared to baseline, they were labelled
‘positive’, otherwise they were labelled ‘negative.’ The data are in a
.csv file called <code>dietData.csv</code>.</p>
<pre class="r"><code>dietData &lt;- read.csv(&#39;data/dietData.csv&#39;, header = T)
dim(dietData)</code></pre>
<pre><code>## [1] 35  2</code></pre>
<pre class="r"><code>names(dietData)</code></pre>
<pre><code>## [1] &quot;id&quot; &quot;x&quot;</code></pre>
<pre class="r"><code>dietData %&gt;% head</code></pre>
<pre><code>##   id        x
## 1  1 positive
## 2  2 positive
## 3  3 positive
## 4  4 positive
## 5  5 positive
## 6  6 positive</code></pre>
<pre class="r"><code>summary(dietData)</code></pre>
<pre><code>##        id            x            
##  Min.   : 1.0   Length:35         
##  1st Qu.: 9.5   Class :character  
##  Median :18.0   Mode  :character  
##  Mean   :18.0                     
##  3rd Qu.:26.5                     
##  Max.   :35.0</code></pre>
<ul>
<li>To perform a hypothesis test, it is useful to explicitly state (for
yourself) what the null hypothesis and alternative hypotheses are.
<ul>
<li><span class="math inline">\(H_0: \pi=0.60\)</span>; the proportion
of individuals who lose 5 of more pounds by week 6 is equal to 0.60</li>
<li><span class="math inline">\(H_a:\pi\ne0.60\)</span>; the proportion
of individuals who lose 5 of more pounds by week 6 not equal to
0.60</li>
</ul></li>
</ul>
<pre class="r"><code>y &lt;- sum(dietData$x == &quot;positive&quot;)
testResults &lt;- binom.test(y, 35, p=0.6) 
testResults$con</code></pre>
<pre><code>## [1] 0.6635017 0.9343782
## attr(,&quot;conf.level&quot;)
## [1] 0.95</code></pre>
<ul>
<li><span class="math inline">\(p\)</span>-value: 0.005</li>
<li>95% confidence interval for <span class="math inline">\(\pi\)</span>
is 0.664 to 0.934</li>
<li>Based on the <span class="math inline">\(p\)</span>-value, we would
reject the null hypothesis because the <span
class="math inline">\(p\)</span>-value &lt; 0.01.</li>
<li>Conclusion: It appears as though the new diet has a
<strong>higher</strong> proportion of individuals who have lost 5 or
more pounds at week 6 compared to baseline (<span
class="math inline">\(p\)</span>-value=0.005). For the new diet, it
appears as though the proportion of patients who lost 5 or more pounds
at week 6 compared to baseline was 0.829 (95% confidence interval: 0.664
to 0.934)</li>
</ul>
<p><br><br><br></p>
<p><a href="toc.html">&lt; Back to Syllabus</a></p>
<p><br><br><br></p>
</div>

<br><br>
<footer>
  <p class="copyright text-muted" align="center">Copyright &copy; 2024 Cold Spring Harbor Laboratory</p>
</footer>


</div>
</div>

</div>

<script>

// add bootstrap table styles to pandoc tables
function bootstrapStylePandocTables() {
  $('tr.odd').parent('tbody').parent('table').addClass('table table-condensed');
}
$(document).ready(function () {
  bootstrapStylePandocTables();
});


</script>

<!-- tabsets -->

<script>
$(document).ready(function () {
  window.buildTabsets("TOC");
});

$(document).ready(function () {
  $('.tabset-dropdown > .nav-tabs > li').click(function () {
    $(this).parent().toggleClass('nav-tabs-open');
  });
});
</script>

<!-- code folding -->

<script>
$(document).ready(function ()  {

    // temporarily add toc-ignore selector to headers for the consistency with Pandoc
    $('.unlisted.unnumbered').addClass('toc-ignore')

    // move toc-ignore selectors from section div to header
    $('div.section.toc-ignore')
        .removeClass('toc-ignore')
        .children('h1,h2,h3,h4,h5').addClass('toc-ignore');

    // establish options
    var options = {
      selectors: "h1,h2,h3,h4",
      theme: "bootstrap3",
      context: '.toc-content',
      hashGenerator: function (text) {
        return text.replace(/[.\\/?&!#<>]/g, '').replace(/\s/g, '_');
      },
      ignoreSelector: ".toc-ignore",
      scrollTo: 0
    };
    options.showAndHide = false;
    options.smoothScroll = false;

    // tocify
    var toc = $("#TOC").tocify(options).data("toc-tocify");
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    script.src  = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML";
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>

</body>
</html>
